table Fotos_Vehiculos
	lineageTag: 0422fbaa-7c30-4a58-9498-cd3361608380

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 62282d9e-389e-4635-b734-225d195d5036
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 98cf82e3-5bf5-4eb6-af40-b68870065f4a
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 01b2bd8d-d113-41a8-a676-ebe753db4e99
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: b1d6e96e-acd1-4bb5-9b44-51e5241f0ffd
		summarizeBy: none
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: 0de17d12-bc05-4ea7-8ccb-cee35f4edf46
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	partition Fotos_Vehiculos = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\osegu\Downloads\VentasVehiculos.xlsx"), null, true),
				    Fotos_Vehiculos_Table = Source{[Item="Fotos_Vehiculos",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Fotos_Vehiculos_Table,{{"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

