table Hoja1
	lineageTag: e3866b76-e92e-4b7b-a27f-3c0f1f107077

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 143e5312-2584-4278-b91d-f9f7dcd3d98e
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 7c033945-8318-4cdd-bfc1-c8a4403854dd
			defaultHierarchy: LocalDateTable_b39cabde-a96d-4cef-b837-b8e5f40075b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: d3c6b83b-8e78-4ac9-b32f-8be109c95d5b
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 8978e17b-59dd-439d-8cb8-17d3a05dc191
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 6ed7c64b-5a9b-4aed-9e5a-6dbf4c7be673
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 86b39692-b1b9-4e3f-a351-98ad41bafaf0
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 8cf31e0a-6249-41b0-b759-e9e45200a8ae
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: cae3acc7-5c13-48c5-b96e-9240af6f0e25
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: c5046c38-9736-4d53-955e-fd3646f5cec4
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: 8c79d33b-ae0d-49ed-a1f5-861de601825d
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: 8146eac9-1c72-40c5-b260-f135e062b16c
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: a57c5868-22de-4d60-94cd-3a1abcdfdc39
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 0acf2694-0065-49f0-8c8d-c562d5ee39a5
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: dfc23a85-2ba3-42d4-8a51-677a9a846330
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: db009f8f-e164-4601-ac29-ffdad4830af7
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 76208952-4943-4f2f-9ebc-73ffd8d8601e
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 018608e7-b7fc-4397-bd59-9bc7570cd8b0
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 26ed6c18-bec6-4061-86f7-fb0b706ea625
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 407599da-c4cb-45a2-9bb8-cbf46f0a2319
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 4b6f7d23-68f5-4d77-bc06-7a49c2f863cb
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: fa5ac554-9bcd-4906-b2cf-17ff8fe1fe07
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 648dfe57-b2e7-46df-bc72-eadb1d48134e
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 895924c3-6948-4b8a-a4fa-4e8f9e0adad7
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 26c966e9-f1d1-4109-b4b7-f76f07da2957
		summarizeBy: sum
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: adf9892e-9665-4747-9757-644c5303b9d4
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: 1f91f819-15f3-40d4-aa4f-1f8411dfb4b5
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column 'mes.1'
		dataType: string
		lineageTag: 40edb6ad-547f-43b3-acac-d5a5fbf15168
		summarizeBy: none
		sourceColumn: mes.1

		annotation SummarizationSetBy = Automatic

	column id_sede_1
		dataType: int64
		formatString: 0
		lineageTag: fd0069d5-67f4-4571-ba66-6b9edd1fe7c4
		summarizeBy: sum
		sourceColumn: id_sede_1

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: 827c0a2e-835b-4c64-878e-1421b11f6e03
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	column Column29
		dataType: string
		lineageTag: 16062d49-382c-40b4-8fb4-c7e42d2e9c8f
		summarizeBy: none
		sourceColumn: Column29

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 504d0a3f-e073-4269-bca3-8dfd54122234
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column datekey_2
		dataType: int64
		formatString: 0
		lineageTag: a664ab55-73ed-4f2f-b01e-00e90558427a
		summarizeBy: sum
		sourceColumn: datekey_2

		annotation SummarizationSetBy = Automatic

	column 'Canal.1'
		dataType: int64
		formatString: 0
		lineageTag: 25b34a83-9a85-46c3-9e09-fb581608ec06
		summarizeBy: sum
		sourceColumn: Canal.1

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: 4ca42617-9a2a-4d74-bc79-9c0124ceedf3
		summarizeBy: sum
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: da4e6e7a-a580-417a-ab95-9b13b01c8c20
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 17786192-474f-4880-99d6-65cc7f10811f
		summarizeBy: sum
		sourceColumn: Vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo Vehículo'
		dataType: double
		lineageTag: 4952879d-1f4f-4239-8b25-9ff1dda8e78b
		summarizeBy: sum
		sourceColumn: Costo Vehículo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Venta sin IGV'
		dataType: double
		lineageTag: 4425ef8a-0073-487e-bbc6-39e390171522
		summarizeBy: sum
		sourceColumn: Precio Venta sin IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IGV
		dataType: double
		lineageTag: 41a301cf-6eaf-4c4e-b289-1f6c9406b3c8
		summarizeBy: sum
		sourceColumn: IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: int64
		formatString: 0
		lineageTag: 589f2b76-abc8-4bcc-92f8-52f8dfb36a58
		summarizeBy: sum
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 359ef125-f321-4c06-875d-ff2a41dad167
		summarizeBy: sum
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Column41
		dataType: string
		lineageTag: 28262c4a-0a37-4f1c-8ba1-5f63b815835b
		summarizeBy: none
		sourceColumn: Column41

		annotation SummarizationSetBy = Automatic

	column 'Id.1'
		dataType: int64
		formatString: 0
		lineageTag: 869e1e68-b22d-4f6a-b371-5e78773734cf
		summarizeBy: sum
		sourceColumn: Id.1

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 391c9f12-4ede-4500-b230-16f0981e9488
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 8cf38f72-6483-4220-a07d-6a34633abe5e
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: 1b2705e2-2d3b-4453-b308-ecffe5678071
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: 7cd1f853-bbd4-43f1-bfc2-6e7acd42cbf2
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	column Column47
		dataType: string
		lineageTag: e19500c0-a007-42b6-9277-8bf1f5c446f5
		summarizeBy: none
		sourceColumn: Column47

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 36692f6c-7b3c-41cb-aa4a-56ad2279de62
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor_3
		dataType: string
		lineageTag: 6c35ed26-ffd7-4057-943f-407fb1054447
		summarizeBy: none
		sourceColumn: Vendedor_3

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: ba767ccf-3326-41c4-88c7-86c5966a9401
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variation
			isDefault
			relationship: 58ea03b0-1d4b-4e4b-9e04-c851ba94cdac
			defaultHierarchy: LocalDateTable_50179232-662b-479f-99f5-627d21817d65.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 3ec5a9ff-2391-45e5-bd5e-c507f120728b
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Hoja1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\osegu\Downloads\VentasVehiculos.xlsx"), null, true),
				    Hoja1_Sheet = Source{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}, {"Column7", type any}, {"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}, {"Column11", type any}, {"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}, {"Column15", type any}, {"id_Cliente", Int64.Type}, {"Nombre", type text}, {"Column18", type any}, {"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}, {"Column24", type any}, {"periodo", Int64.Type}, {"mes", type text}, {"id_sede_1", Int64.Type}, {"ppto", Int64.Type}, {"Column29", type any}, {"ID", Int64.Type}, {"datekey_2", Int64.Type}, {"Canal", Int64.Type}, {"Cliente", Int64.Type}, {"Segmento", type text}, {"Vehiculo", Int64.Type}, {"Costo Vehículo", type number}, {"Precio Venta sin IGV", type number}, {"IGV", type number}, {"Sede", Int64.Type}, {"Vendedor", Int64.Type}, {"Column41", type any}, {"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}, {"Column47", type any}, {"ID_Vendedor", Int64.Type}, {"Vendedor_3", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"mes", "mes.1"}, {"Canal", "Canal.1"}, {"Id", "Id.1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

